#!/usr/bin/env bash

if [ $# == 0 ]; then
    echo "Usage: sysInfo <sys|mem|disk>"
    exit
fi

for arg in $@; do
    if [ $arg == "sys" ]; then
        echo "---------------System Information--------------"
        echo -e "Hostname:\t\t" $(cat /proc/sys/kernel/hostname)
        echo -e "uptime:\t\t\t" $(uptime -p)
        echo -e "Manufacturer:\t\t" $(cat /sys/class/dmi/id/sys_vendor)
        echo -e "Product Name:\t\t" $(cat /sys/class/dmi/id/product_name)
        echo -e "Version:\t\t" $(cat /sys/class/dmi/id/product_version)
        echo -e "Machine Type:\t\t" $(vserver=$(lscpu | grep Hypervisor | wc -l); if [ $vserver -gt 0 ]; then echo "VM"; else echo "Physical"; fi)
        echo -e "Operating System:\t" $(grep -o 'Ubuntu ' /etc/os-release) $(awk 'NR==1{print $2}' /etc/os-release) $(awk 'NR==1{print $3}' /etc/os-release)
        echo -e "Kernel:\t\t\t" $(uname -r)
        echo -e "Architecture:\t\t" $(uname -p)
        echo -e "Processor Name:\t\t" $(awk -F':' '/^model name/ {print $2}' /proc/cpuinfo | uniq | sed -e 's/^[ \t]*//')
        echo -e "Active User:\t\t" $(whoami)
        echo -e "Main System IP:\t\t" $(hostname -I)
    elif [ $arg == "mem" ]; then
        echo "------------------CPU/Memory Usage---------------"
        command free
        echo -e "Memory\t\t" $(cat /proc/stat | awk '/cpu/{printf("%.2f%%\n"), ($2+$4)*100/($2+$4+$5)}' | awk '{print $0}' | head -1)
        echo -e "Swap\t\t" $(free -t | awk 'FNR == 3 {printf("%.2f%%\n"), ($3/$2*100)}')
        echo -e "CPU:\t\t" $(top -b -n1 | grep ^%Cpu | awk '{printf("%.2f%%\n"), 100-$8}')

    elif [ $arg == "disk" ]; then
        echo "---------------------Disk Usage------------------"
        echo $(df -h | awk '$NF=="/"{printf "Disk Usage: %s\t\t\n\n", $5}')
        command df -ha | grep "loop"
    else
        echo "Error, invalid parameter."
        exit
    fi
done
